version: '3.9'

name:  boilerplate_raw_change_me

services:

  postgres:
    container_name: postgres_${PROJECT_NAME}
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin_${PROJECT_NAME}
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: ${PGADMIN_LISTEN_PORT}
    ports:
      - "5050:5050"
    depends_on:
      - postgres

  redis:
    container_name: redis_${PROJECT_NAME}
    image: redis:latest
    ports:
      - "6379:6379"
  nginx:
    container_name: nginx_${PROJECT_NAME}
    image: nginx:latest
    volumes:
      - ./NGINX:/etc/nginx/conf.d
      - static_volume:/app/static/
      - media_volume:/app/media/
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    container_name: backend_server
    build:
      context: .
      dockerfile: Docker/DockerfileBackend
      args:
        ENV_FILE: .env
    ports:
      - "8005:8000"
    volumes:
      - static_volume:/app/static/
      - media_volume:/app/media/
    depends_on:
      - postgres
      - redis


volumes:
  static_volume:
  media_volume: