# Generated by Django 4.2.4 on 2024-04-30 09:09

import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('birthdate', models.DateField(default=django.utils.timezone.now, verbose_name='birth date')),
                ('mobile_number', models.BigIntegerField(blank=True, null=True, verbose_name='mobile number')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='description')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='location')),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now, verbose_name='last seen')),
                ('is_banned', models.BooleanField(default=False, verbose_name='banned')),
                ('is_vip', models.BooleanField(default=False, verbose_name='vip')),
                ('is_kyc_l1_done', models.BooleanField(default=False, verbose_name='KYC 1')),
                ('is_kyc_l2_done', models.BooleanField(default=False, verbose_name='KYC 2')),
                ('is_premium', models.BooleanField(default=False, verbose_name='premium')),
                ('bio', models.TextField(blank=True)),
                ('rating', models.FloatField(default=0)),
                ('irr_balance', models.FloatField(default=0)),
                ('total_balance', models.FloatField(default=0)),
                ('freeze_balance', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
    ]
